version: '3.9'

services:  
  nginx:
    image: nginx 
    ports:
      - 3001:80
      - 3002:443
    configs:
      - source: config_nginx
        target: /etc/nginx/templates/default.conf.template
    environment:
      APP_HOST: api
    networks: 
      - public

  api:
    image: localhost:5000/api:latest
    command: ['./config/wait-for-it.sh', 'database', '--', './config/wait-for-it.sh', 'cache', '--', 'echo', 'ok']
    secrets:
      - secret_mysql_password
    environment:
      MYSQL_HOST: database 
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: /run/secrets/secret_mysql_password 
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - public
      - private

  database:
    image: mysql 
    configs:
      - source: config_mysql
        target: /docker-entrypoint-initdb.d/init.sql  
    secrets:
      - secret_mysql_password
    environment:
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: /run/secrets/secret_mysql_password  
    volumes:
      - db:/home/lib/mysql
    networks:
      - private
    healthcheck:
      test: mysql -p$$MYSQL_ROOT_PASSWORD --silent -e 'SHOW DATABASES;'
      interval: 3s
      timeout: 3s
      retries: 10

  cache:
    image: redis
    entrypoint: redis-server
    command: --save 60 1 --loglevel warning 
    volumes:
      - cache:/data
    networks: 
      - private
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 3s
      retries: 10

  monitoring:
    image: prom/prometheus 
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - public
      - private

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - public
      - private

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         - node.hostname == manager
    networks:
      - public
      - private

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://192.168.33.2:3001/metrics
    ports:
      - 9113:9113
    deploy:
      placement:
        constraints:
         - node.hostname == manager
    networks:
      - public
      - private

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - public
      - private
    deploy:
      placement:
        constraints:
          - node.role == manager

configs:
  config_mysql:
    file: ./config/mysql/init.sql 
  config_nginx:
    file: ./config/nginx/templates/default.conf.template

secrets:
  secret_mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: 1

volumes:
  db: {}
  cache: {}
  grafana: {}
