global:
  scrape_interval:     15s .
  evaluation_interval: 15s  
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
scrape_configs:
  - job_name: 'prometheus'
    
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'

    static_configs:
      - targets: ['192.168.33.2:9323']
