global:
  scrape_interval: 15s 
  evaluation_interval: 15s  
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - service_cadvisor:8080
